### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by marcuswhybrow** [marcuswhybrow/ray-peat-rodeo#47]
Running
```
nix build github:marcuswhybrow/ray-peat-rodeo
```

Gives
```
❯ nix log /nix/store/jc6l6ifb7p94afrs8pk9jxbax06gamib-build-unstable.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/jc6l6ifb7p94afrs8pk9jxbax06gamib-build-unstable.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8l929rs8d558wap3i96040vydr478vxk-fpvihycy8cambyzs4cajh9xy9yk0h0fk-source
source root is fpvihycy8cambyzs4cajh9xy9yk0h0fk-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building Ray Peat Rodeo...
2023/11/25 04:53:01 Scanning files in ./assets
fatal error: concurrent map writes

goroutine 8 [running]:
github.com/marcuswhybrow/ray-peat-rodeo/internal/cache.(*HTTPCache).request(0xc00027f8f0, 0xc000498400, {0x98d93d, 0x5}, 0x9d7cc0)
        github.com/marcuswhybrow/ray-peat-rodeo/internal/cache/cache.go:94 +0x9d
github.com/marcuswhybrow/ray-peat-rodeo/internal/cache.(*HTTPCache).Get(0xc0008a7ae8?, {0xc0008403c0, 0x39}, {0x98d93d, 0x5}, 0xaa12c0?)
        github.com/marcuswhybrow/ray-peat-rodeo/internal/cache/cache.go:86 +0x9a
github.com/marcuswhybrow/ray-peat-rodeo/internal/markdown/parser.(*githubIssueParser).Parse(0xaa12c0?, {0xc0003bec80?, 0xc0003bec80?}, {0xa9c610, 0xc000527800}, {0xa9d000, 0xc0003b0000})
        github.com/marcuswhybrow/ray-peat-rodeo/internal/markdown/parser/github_issue.go:62 +0x1b1
github.com/yuin/goldmark/parser.(*parser).parseBlock(0xc00022f500, {0xa9cdb8?, 0xc000527800}, {0xaa12c0, 0xc0003bec80}, {0xa9d000, 0xc0003b0000})
        github.com/yuin/goldmark/parser/parser.go:1208 +0x969
github.com/yuin/goldmark/parser.(*parser).Parse.func2({0xaa12c0?, 0xc0003bec80?})
        github.com/yuin/goldmark/parser/parser.go:880 +0x3d
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xaa0420?, {0xaa12c0, 0xc0003bec80}, 0xc0003e1e08)
        github.com/yuin/goldmark/parser/parser.go:1133 +0x79
github.com/yuin/goldmark/parser.(*parser).walkBlock(0x9698c0?, {0xaa0420, 0xc0003d7b00}, 0xc0008a7e08)
        github.com/yuin/goldmark/parser/parser.go:1131 +0x4c
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc000398000?, {0xaa0e40, 0xc0003b4000}, 0xc0008a7e08)
        github.com/yuin/goldmark/parser/parser.go:1131 +0x4c
github.com/yuin/goldmark/parser.(*parser).Parse(0xc00022f500, {0xa9c560, 0xc0003b0070}, {0xc000392010, 0x1, 0x411f45?})
        github.com/yuin/goldmark/parser/parser.go:879 +0x1f3
github.com/yuin/goldmark.(*markdown).Convert(0xc000202300, {0xc000398000, 0x98c0, 0x98c1}, {0xa958c0, 0xc0003aa090}, {0xc000392010, 0x1, 0x1})
        github.com/yuin/goldmark/markdown.go:116 +0xce
main.main.func2({0xc00002ecc0?, 0x0?})
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/main.go:116 +0x1f9
created by main.main in goroutine 1
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/main.go:106 +0x6d3

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00043b060?)
        runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc0002a0000?)
        sync/waitgroup.go:116 +0x48
main.main()
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/main.go:141 +0x892

goroutine 6 [runnable]:
```

and later

```
goroutine 7 [semacquire]:
os.ReadFile({0xc00002ebc0?, 0x0?})
        os/file.go:738 +0xe5
main.NewFile({0xc00002ebc0, 0x37})
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/file.go:40 +0x138
main.main.func2({0xc00002ebc0?, 0x0?})
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/main.go:109 +0xab
created by main.main in goroutine 1
        github.com/marcuswhybrow/ray-peat-rodeo/cmd/ray-peat-rodeo/main.go:106 +0x6d3
```

**Comment by marcuswhybrow** [comment]
I think this is the error causing #45.
